export const content = {
  riskIndex: '85',
  riskStatus: 'ELEVATED',

  riskMonitor: {
    updated: 'August 25, 2026 09:00 UTC',
    overallScore: 85,
    trend: 'EASING',
    drivers: ['Nigeria Niger State: 600 Kidnapped In Mosque Attack — 30 Killed — 2,000 Flee To Benin Republic — Tinubu Orders Rescue', 'Ebola DRC 2,690 Dead — 5,514 Cases — 47.9% CFR — Now Approaching 2014-16 West Africa As Worst Ever', 'Tanzania VP Nchimbi Resigns Less Than A Year Into Office — East Africa Political Instability Signal', 'SA Employers Fired Foreign Workers Under March And March Threats — Enforcement Nexus Confirmed'],
    regions: [
      { region: 'East Africa', score: 88, trend: '↑', color: '#f5a623' },
      { region: 'West Africa', score: 84, trend: '↑', color: '#f5a623' },
      { region: 'North Africa', score: 80, trend: '→', color: '#f5a623' },
      { region: 'Southern Africa', score: 70, trend: '→', color: '#f5a623' },
      { region: 'Central Africa', score: 99, trend: '↑', color: '#ff3b3b' },
    ]
  },

  sovereignAlerts: [
    { country: 'Nigeria', flag: '🇳🇬', alert: 'NIGER STATE MASS KIDNAPPING: 600 TAKEN — 30 KILLED — 2,000 FLEE TO BENIN REPUBLIC. President Tinubu ordered security agencies to launch an immediate rescue operation after gunmen kidnapped scores of people in Niger State — a video circulating online suggests about 600 women, children, and older people were taken during a mosque attack last week. A local official confirmed 30 people killed and buried Sunday. The traditional head of the Dakera community said at least 2,000 residents fled into neighboring Benin Republic. This follows the Plateau Bin-Per massacre of 26 people (August 18) — Nigeria is simultaneously managing mass kidnapping in Niger State, massacre in Plateau, ISSP in Kebbi/Sokoto, ISWAP in Borno, and Boko Haram attacks. Banditry and mass kidnapping in the northwest-northcentral zone has never been worse. NGN at 1,347 — strongest since February 2026 — YTD -12.04% from August 2025 levels.', severity: 'CRITICAL', color: '#ff3b3b' },
    { country: 'DRC', flag: '🇨🇩', alert: 'EBOLA: 2,690 DEAD — 5,514 CASES — 47.9% CFR — APPROACHING WORST IN HISTORY. As of August 25, 5,514 confirmed cases and 2,690+ deaths — a 47.9% case fatality rate. The outbreak is now approaching the 2014-2016 West Africa epidemic (11,310 deaths) at a pace that, if sustained, could surpass it within months. WHO updated its recommendations to member states — DRC remains the only country ranked "very high" risk, with neighbors Burundi and Central African Republic now ranked "high risk." MSF has deployed 1,400+ staff. The outbreak is spreading beyond Ituri into neighboring countries\' risk zones. This is the most dangerous public health emergency on the continent in a decade.', severity: 'CRITICAL', color: '#ff3b3b' },
    { country: 'Tanzania', flag: '🇹🇿', alert: 'VICE PRESIDENT NCHIMBI RESIGNS — LESS THAN A YEAR INTO OFFICE. Tanzania\'s Vice-President Emmanuel Nchimbi has resigned, less than a year after taking office alongside President Samia Suluhu Hassan. No official reason given immediately. This is a significant political signal for East Africa\'s largest economy — a VP resignation at this stage of the electoral cycle raises questions about internal ANC-Chama Cha Mapinduzi dynamics and the succession picture ahead of Tanzania\'s upcoming general election. Tanzania is under international scrutiny over mass arrests (130 arrested in August) and a reimposed political rally ban. TZS at 2,624.', severity: 'HIGH', color: '#ff3b3b' },
    { country: 'South Africa', flag: '🇿🇦', alert: '"FIRED FOR BEING FOREIGN" — EMPLOYERS GAVE IN TO MARCH AND MARCH THREATS. A major new investigation confirms that South African employers are firing foreign workers under direct threats from March and March — the enforcement nexus extends beyond the state into the private economy. Combined with the March and March-AfriForum alliance formalised this week, the December 31 year-end ultimatum for workplace quotas now has street enforcement, legal resources, and economic compliance simultaneously. SA anti-immigrant violence slows SDG goals and rips apart Africans\' free movement framework. Starlink pushing for SA market entry after years of regulatory delays. ZAR 16.01 — strongest in months.', severity: 'HIGH', color: '#ff3b3b' },
    { country: 'Zimbabwe', flag: '🇿🇼', alert: 'MNANGAGWA DRAGGED TO CONSTITUTIONAL COURT — SENATE PACKING. Mnangagwa has been taken to the Constitutional Court, accused of packing the Senate with ZANU-PF politicians — a direct challenge to constitutional governance. Zimbabwe opposition leader Chamisa has dismissed the CCC (Citizens Coalition for Change) as "Kids\' Play" and teased a new political movement. ZANU-PF Harare Province is pushing for Mnangagwa\'s term to be extended to 2037 — the 2030 extension was signed in July. Multiple simultaneous constitutional challenges from different directions — ConCourt challenge on 2030 extension, ConCourt challenge on Senate packing, opposition movement reconstitution.', severity: 'HIGH', color: '#ff3b3b' },
  ],

  featuredSignal: {
    title: 'NIGERIA 600 KIDNAPPED 30 KILLED NIGER STATE — EBOLA 2,690 DEAD 47.9% CFR APPROACHING WORST EVER — TANZANIA VP RESIGNS — EMPLOYERS FIRE FOREIGN WORKERS — MNANGAGWA CONCOURTCHALLENGE',
    body: 'August 25 delivers the week\'s heaviest signal day. Nigeria\'s compound security crisis reaches a new peak: 600 people kidnapped during a mosque attack in Niger State (30 killed, 2,000 fled to Benin Republic), on top of the Plateau Bin-Per massacre of 26 (August 18). Tinubu ordered an immediate rescue operation. Ebola in DRC has now killed 2,690 with 5,514 confirmed cases and a 47.9% CFR — approaching the 2014-2016 West Africa epidemic at a pace that could see it surpass it within months. Tanzania\'s Vice-President Nchimbi resigned less than a year into office — a significant political signal for East Africa\'s largest economy. SA employers are being documented firing foreign workers under direct March and March threats — the enforcement nexus has moved into the private economy. Mnangagwa was dragged to the Constitutional Court over Senate packing. Chamisa teases a new Zimbabwe opposition movement. ZAR at 16.01 — strongest since early 2026. NGN at 1,347 — 12.04% stronger than August 2025. US pushing expanded UN sanctions on Sudan. Guinea-Bissau planning a referendum to expand presidential power.',
    tag: 'AUGUST 25 CRITICAL SIGNAL',
    color: '#ff3b3b',
    author: 'Lord Fiifi Quayle',
    date: 'August 25, 2026',
  },

  pressureMap: [
    { country: 'Nigeria', flag: '🇳🇬', outlook: 'Negative', status: 'STRESSED', statusColor: '#ff3b3b', cds: '360', fxPressure: 'LOW', liquidity: 'IMPROVING' },
    { country: 'Ghana', flag: '🇬🇭', outlook: 'Positive', status: 'STABLE', statusColor: '#00c48c', cds: '205', fxPressure: 'LOW', liquidity: 'STABLE' },
    { country: 'Kenya', flag: '🇰🇪', outlook: 'Cautious', status: 'WATCH', statusColor: '#f5a623', cds: '192', fxPressure: 'MODERATE', liquidity: 'WATCH' },
    { country: 'South Africa', flag: '🇿🇦', outlook: 'Cautious', status: 'WATCH', statusColor: '#f5a623', cds: '178', fxPressure: 'LOW', liquidity: 'STABLE' },
    { country: 'Tanzania', flag: '🇹🇿', outlook: 'Negative', status: 'WATCH', statusColor: '#f5a623', cds: '0', fxPressure: 'MODERATE', liquidity: 'WATCH' },
    { country: 'Ivory Coast', flag: '🇨🇮', outlook: 'Positive', status: 'STABLE', statusColor: '#00c48c', cds: '178', fxPressure: 'LOW', liquidity: 'IMPROVING' },
  ],

  whatMattersNow: [
    { title: 'NIGERIA NIGER STATE: 600 KIDNAPPED — 30 KILLED — 2,000 FLEE TO BENIN REPUBLIC — TINUBU ORDERS RESCUE', body: '< cite index="2-1">Nigerian President Tinubu ordered security agencies today to launch an immediate rescue operation after gunmen kidnapped scores of people, with a video circulating online suggesting about 600 women, children, and older people were taken during a mosque attack last week — a local official said 30 people were killed in the attack and buried Sunday, while the traditional head of the Dakera community said at least 2,000 residents fled into neighboring Benin Republic.</cite> This is a catastrophic security failure in Niger State — the same geopolitical zone where bandits and kidnappers have operated with relative impunity for years. The mass kidnapping at a mosque, with 600 captives and 2,000 residents displaced across the border into Benin, is one of the largest single kidnapping events in Nigerian history.', icon: '🚨' },
    { title: 'EBOLA: 2,690 DEAD — 47.9% CFR — APPROACHING WORST OUTBREAK IN HISTORY', body: '< cite index="2-1">As of Monday August 25, the DRC Ebola outbreak had recorded 5,514 confirmed cases and more than 2,690 deaths, a fatality rate of 47.9% — WHO updated its recommendations to member states, with DRC still the only country ranked "very high" risk, and neighbors Burundi and the Central African Republic now ranked "high risk."</cite> At 2,690 dead the outbreak is now approaching the second milestone: the 2014-2016 West Africa epidemic (11,310 deaths) was the worst in history. The current outbreak, at 47.9% CFR vs the 2014-2016 epidemic\'s ~40%, has a higher kill rate. If sustained, the trajectory implies the current outbreak could surpass West Africa 2014-2016 in total deaths within several months.', icon: '🔴' },
    { title: 'TANZANIA VP NCHIMBI RESIGNS — POLITICAL SIGNAL — EAST AFRICA ELECTORAL CYCLE', body: '< cite index="2-1">Tanzania\'s Vice-President Emmanuel Nchimbi resigned less than a year into office.</cite> The VP resignation is the most significant political signal from Tanzania since Samia Suluhu Hassan assumed the presidency following John Magufuli\'s death in 2021. No official reason was immediately given. The timing — ahead of Tanzania\'s upcoming general election, amid international scrutiny over 130 arrests and the reimposed political rally ban — suggests internal CCM dynamics are under strain. Tanzania is East Africa\'s largest economy (ahead of Kenya by some measures), and its political stability has been assumed by regional investors. TZS at 2,624 — a VP resignation is a medium-term political risk signal.', icon: '⚠️' },
    { title: 'SA: EMPLOYERS FIRED FOREIGN WORKERS UNDER MARCH AND MARCH THREATS — ENFORCEMENT INTO PRIVATE ECONOMY', body: '< cite index="1-1">South Africa: "Fired for Being Foreign — How Employers Gave in to March and March Threats" — a major investigation published today confirming that South African employers are dismissing foreign workers under direct threats from March and March.</cite> This is a qualitative escalation: the xenophobia campaign has moved from street protest (June-July) through state enforcement (53,499 deportations) through vigilante-police handovers (July 27) to private economy compliance. Employers are now participating in the migration enforcement architecture without state compulsion — driven by fear of March and March threats. The March and March-AfriForum alliance adds legal and advocacy infrastructure to this enforcement model entering December 31.', icon: '🔥' },
  ],

  insight1: {
    title: 'NIGERIA\'S COMPOUND SECURITY CRISIS — 600 KIDNAPPED, 26 MASSACRED, ISSP, ISWAP, BOKO HARAM SIMULTANEOUSLY — IS THE WORST MULTI-VECTOR THREAT IN THE COUNTRY\'S HISTORY',
    body: 'Nigeria is simultaneously managing: (1) Niger State mass kidnapping — 600 taken, 30 killed, 2,000 fled to Benin; (2) Plateau Bin-Per massacre — 26 killed August 18; (3) ISSP operations in Kebbi and Sokoto — first entry in 6 years, Lakurawa militants confirmed; (4) ISWAP/Boko Haram in Borno — 104 soldiers missing after June ISWAP attack; (5) Northwest banditry — ongoing mass kidnapping operations across Zamfara, Sokoto, Katsina. This compound security crisis operates simultaneously with the country\'s strongest macro year in decades: NSE 160 trillion naira, reserves $50.12bn 17-year high, NGN at 1,347 (12.04% stronger than August 2025), Dangote Refinery at 700,000 bpd, $5bn IPO October. The structural paradox of Nigeria is at its sharpest: the macro transformation is real; the security collapse is also real; they are happening to different populations in different parts of the same country simultaneously.',
    conclusion: 'NIGERIA\'S COMPOUND SECURITY CRISIS IS THE WORST MULTI-VECTOR THREAT IN THE COUNTRY\'S HISTORY — FIVE SIMULTANEOUS ACTIVE SECURITY EMERGENCIES ACROSS DIFFERENT REGIONS. IT OPERATES SIMULTANEOUSLY WITH THE STRONGEST MACRO YEAR IN DECADES. THE STRUCTURAL PARADOX HAS NEVER BEEN MORE ACUTE.',
  },

  insight2: {
    title: 'EBOLA AT 47.9% CFR WITH 2,690 DEAD IS NOW ON TRAJECTORY TO BECOME THE DEADLIEST OUTBREAK IN HUMAN HISTORY',
    body: 'The 2014-2016 West Africa Ebola outbreak — 11,310 deaths over two years — was the worst in recorded history. The current Bundibugyo outbreak: 2,690 deaths in approximately 14 weeks, 47.9% CFR. The 2014-2016 epidemic had a ~40% average CFR. The current outbreak is killing a higher proportion of those infected. Mathematical extrapolation — if the current pace continues — suggests the current outbreak could surpass 11,310 deaths within 6-8 months from now. This is not a forecast; it is a trajectory that can be broken with adequate funding, healthcare worker deployment, and community trust. But the $1.4bn funding gap from both Africa CDC and the White House Congress ask remains unaddressed. Burundi and CAR are now rated "high risk" by WHO — the outbreak is spreading to its neighbors\' risk zones. The MSF has 1,400+ staff deployed. This is a global health emergency that the world is not adequately resourcing.',
    conclusion: 'EBOLA AT 47.9% CFR AND 2,690 DEAD IS ON TRAJECTORY — IF CURRENT PACE CONTINUES — TO BECOME THE DEADLIEST OUTBREAK IN HUMAN HISTORY WITHIN 6-8 MONTHS. THE $1.4BN FUNDING GAP REMAINS UNADDRESSED. BURUNDI AND CAR NOW RATED HIGH RISK. THIS IS THE MOST URGENT PUBLIC HEALTH EMERGENCY ON EARTH.',
  },

  brief: {
    week: '35',
    title: 'WEEK 35 TUESDAY AUGUST 25: NIGERIA 600 KIDNAPPED 30 KILLED NIGER STATE, EBOLA 2690 DEAD 47.9% CFR WORST IN HISTORY TRAJECTORY, TANZANIA VP RESIGNS, SA EMPLOYERS FIRE FOREIGN WORKERS, MNANGAGWA CONCOURTCHALLENGE',
    body: 'August 25 — the most consequential Tuesday in recent memory. Nigeria\'s security crisis reaches new heights: 600 kidnapped in a mosque attack in Niger State (30 killed, 2,000 fled to Benin Republic), Tinubu ordered an immediate rescue operation — compounding the August 18 Plateau massacre of 26. Ebola in DRC has now killed 2,690 at a 47.9% CFR — on trajectory to become the deadliest outbreak in human history if current pace continues. Burundi and CAR now rated "high risk" by WHO. Tanzania\'s VP resigned less than a year into office. SA employers are documented firing foreign workers under March and March threats — enforcement has moved into the private economy. Mnangagwa was taken to the Constitutional Court over Senate packing. Chamisa teases a new Zimbabwe opposition movement. US pushing expanded UN sanctions on Sudan. Guinea-Bissau planning a referendum to expand presidential power. ZAR at 16.01 — strongest since early 2026. NGN at 1,347 — 12.04% stronger than August 2025. Gold $4,461 ATH. The compound risk environment remains at maximum density.',
  },

  fxRates: {
    NGN: '1,347.00',
    GHS: '11.05',
    KES: '129.50',
    EGP: '52.22',
    XOF: '574.71',
    ZAR: '16.01',
    ETB: '158.50',
    TZS: '2,624.00',
    UGX: '3,674.80',
    MAD: '9.75',
    XAF: '615.00',
    ZMW: '19.02',
    AOA: '915.00',
    MZN: '63.80',
  },

  signals: [
    { time: '09:30:00', signal: 'NIGERIA NIGER STATE: 600 kidnapped in mosque attack. 30 killed. 2,000 residents fled into Benin Republic. Tinubu ordered immediate rescue operation today. Dakera community head confirms mass displacement. Video circulating online of 600 women, children, older people. Largest single kidnapping event in Nigerian history. Compounds Plateau Bin-Per massacre (26 killed August 18). Five simultaneous security vectors active.', detail: 'HIGH', type: 'ALERT', tag: 'SECURITY RISK', country: 'NGN' },
    { time: '09:15:00', signal: 'EBOLA DRC: 2,690 dead — 5,514 confirmed — 47.9% CFR as of August 25. DRC "very high" risk per WHO. Burundi and CAR now "high risk." MSF 1,400+ staff deployed. WHO updated recommendations August 25. Second meeting of IHR Emergency Committee. Trajectory: if current pace continues, could surpass 2014-2016 West Africa (11,310 deaths) in 6-8 months. $1.4bn funding gap unaddressed. Worst public health emergency on earth.', detail: 'HIGH', type: 'ALERT', tag: 'HEALTH RISK', country: 'AFRICA' },
    { time: '09:00:00', signal: 'TANZANIA VP NCHIMBI RESIGNS — less than a year into office. No official reason immediately given. Significant signal for East Africa\'s largest economy. Timing: ahead of upcoming general election, amid 130 arrests and rally ban. Internal CCM dynamics under strain. TZS at 2,624. Tanzania under international scrutiny over democratic backsliding. East Africa electoral cycle signal.', detail: 'HIGH', type: 'ALERT', tag: 'POLITICAL RISK', country: 'TZS' },
    { time: '08:45:00', signal: 'SA: "Fired for Being Foreign" — employers giving in to March and March threats. Enforcement nexus confirmed in private economy. March and March-AfriForum alliance formalised. December 31 ultimatum for workplace quotas now has street enforcement, legal resources, and private sector compliance simultaneously. SA anti-immigrant violence slows SDG goals. Starlink pushing SA market entry. ZAR 16.01 — strongest since early 2026.', detail: 'HIGH', type: 'ALERT', tag: 'POLITICAL RISK', country: 'ZAR' },
    { time: '08:30:00', signal: 'ZIMBABWE: Mnangagwa dragged to Constitutional Court — accused of packing Senate with ZANU-PF politicians. Chamisa dismisses CCC as "Kids\' Play" — teases new political movement. ZANU-PF Harare pushing 2037 extension. Anti-amendment protests. Multiple simultaneous constitutional challenges. US pushing expanded UN sanctions on Sudan. Guinea-Bissau referendum to expand presidential power. Ethiopia bids for AFCON 2028.', detail: 'HIGH', type: 'ALERT', tag: 'POLITICAL RISK', country: 'AFRICA' },
    { time: '08:15:00', signal: 'FX LIVE August 25: ZAR 16.01 (Currency.wiki confirmed 01:05 AM UTC — 0.06240 per dollar) | NGN 1,347 (YTD -12.04% from Aug 2025 high 1,535) | KES 129.50 | XOF 574.71 | ETB 158.50 | UGX 3,674.80 | GHS ~11.05 (Reuters Aug 20: back under pressure, recovering from 10.90 Aug 16 low). ZAR strengthens 1% from 16.16 to 16.01 — gold $4,461 ATH structural floor. NGN at strongest since February 2026.', detail: 'LOW', type: 'INFO', tag: 'FX UPDATE', country: 'AFRICA' },
    { time: '08:00:00', signal: 'Senegal: IMF Q3 programme — Faye-Sonko constitutional court war. First African Olympic event October. Patrick Vieira new Senegal coach. Zambia: Hichilema declared winner 61% — incoming SADC chair. Lobito Corridor secured. SARB September rate cut expected — SA inflation 4.3%, food at 16-year low. Nigeria NSE 160tn naira. Dangote $5bn IPO October. Agricultural commodity surge: corn +10%, wheat +3.9% — Africa food import cost risk. Africa GEF largest beneficiary of GEF funding.', detail: 'MEDIUM', type: 'INFO', tag: 'GEOPOLITICAL', country: 'AFRICA' },
  ],

  heatMap: [
    { country: 'Nigeria', flag: '🇳🇬', score: 78, fiscal: 46, fx: 36, debt: 48, political: 82, external: 76 },
    { country: 'Ghana', flag: '🇬🇭', score: 14, fiscal: 10, fx: 22, debt: 10, political: 16, external: 14 },
    { country: 'Tanzania', flag: '🇹🇿', score: 80, fiscal: 60, fx: 56, debt: 62, political: 90, external: 72 },
    { country: 'Ethiopia', flag: '🇪🇹', score: 98, fiscal: 70, fx: 72, debt: 90, political: 99, external: 98 },
    { country: 'South Africa', flag: '🇿🇦', score: 62, fiscal: 44, fx: 28, debt: 48, political: 72, external: 60 },
    { country: 'Zimbabwe', flag: '🇿🇼', score: 96, fiscal: 74, fx: 82, debt: 80, political: 99, external: 88 },
    { country: 'Zambia', flag: '🇿🇲', score: 48, fiscal: 44, fx: 62, debt: 46, political: 38, external: 46 },
    { country: 'DRC', flag: '🇨🇩', score: 99, fiscal: 88, fx: 90, debt: 82, political: 96, external: 99 },
  ],

  currencyStress: [
    { code: 'NGN', country: 'Nigeria', rate: '1,347.00', change: '-12.04%', stress: 'LOW', ytd: '-12.04%', color: '#00c48c' },
    { code: 'GHS', country: 'Ghana', rate: '11.05', change: '+5.20%', stress: 'LOW', ytd: '+5.20%', color: '#00c48c' },
    { code: 'KES', country: 'Kenya', rate: '129.50', change: '+0.19%', stress: 'MODERATE', ytd: '-0.93%', color: '#f5a623' },
    { code: 'EGP', country: 'Egypt', rate: '52.22', change: '-4.32%', stress: 'HIGH', ytd: '-4.51%', color: '#ff3b3b' },
    { code: 'ZAR', country: 'South Africa', rate: '16.01', change: '-11.95%', stress: 'LOW', ytd: '+11.95%', color: '#00c48c' },
    { code: 'UGX', country: 'Uganda', rate: '3,674.80', change: '-1.92%', stress: 'LOW', ytd: '-1.92%', color: '#00c48c' },
    { code: 'ZMW', country: 'Zambia', rate: '19.02', change: '-32.91%', stress: 'MODERATE', ytd: '-32.91%', color: '#f5a623' },
    { code: 'XOF', country: 'WAEMU', rate: '574.71', change: '-6.59%', stress: 'MODERATE', ytd: '-6.59%', color: '#f5a623' },
  ],

  elections: [
    { country: 'Tanzania', flag: '🇹🇿', date: 'VP Nchimbi Resigned — Electoral Cycle Signal', type: 'General Election', risk: 'HIGH', note: 'VP resigned less than a year into office. No reason given. Ahead of upcoming general election. 130 arrested, rally ban reimposed. East Africa\'s largest economy political signal. TZS at 2,624.', color: '#ff3b3b' },
    { country: 'Zambia', flag: '🇿🇲', date: 'Hichilema WINS 61% — Incoming SADC Chair', type: 'General Election', risk: 'LOW', note: 'Declared: 2.97m vs Mundubile 1.86m. Opposition legal challenge pending. ZMW stabilising. Lobito $255m secured. SADC democratic model validated. IMF reform model survives.', color: '#00c48c' },
    { country: 'South Africa', flag: '🇿🇦', date: 'Fall 2026 — Private Economy Enforcement', type: 'Municipal Elections', risk: 'HIGH', note: 'Employers fired foreign workers under March and March threats. Private economy enforcement confirmed. December 31 ultimatum institutionalised. PEPFAR September expiry. ZAR 16.01. SARB cut expected.', color: '#f5a623' },
    { country: 'Zimbabwe', flag: '🇿🇼', date: 'Mnangagwa ConCourt — Senate Packing — 2037', type: 'Constitutional Amendment', risk: 'CRITICAL', note: 'Mnangagwa dragged to ConCourt over Senate packing. ZANU-PF pushing 2037. Chamisa teases new movement. Multiple simultaneous constitutional challenges.', color: '#ff3b3b' },
    { country: 'Senegal', flag: '🇸🇳', date: 'Faye vs Sonko — Constitutional Court', type: 'Constitutional Referendum', risk: 'CRITICAL', note: 'Faye launched Kiiraay — goes to Sonko\'s Constitutional Court. IMF Q3 at maximum risk. First African Olympic event October.', color: '#ff3b3b' },
    { country: 'DRC', flag: '🇨🇩', date: 'Ebola 2,690 Dead — C64 Post-Deadline', type: 'Constitutional Crisis', risk: 'CRITICAL', note: 'Ebola 2,690 dead 47.9% CFR — on trajectory to worst in history. Burundi CAR now high risk. C64 August 15 deadline passed — outcome unclear. Constitutional and health crises simultaneous.', color: '#ff3b3b' },
    { country: 'Ethiopia', flag: '🇪🇹', date: 'Tigray Fano Expanding — AFCON 2028 Bid', type: 'General Election', risk: 'CRITICAL', note: 'Fano insurrection expanding. Ethiopia also bids to host AFCON 2028. Draws against Senegal, Mozambique, Sudan in AFCON 2027. Horn most dangerous since 2020.', color: '#ff3b3b' },
  ],

  debtMaturities: [
    { country: 'Nigeria', flag: '🇳🇬', amount: '$5bn', instrument: 'Dangote Refinery IPO', maturity: 'OCTOBER 2026 — SECURITY CRISIS COMPOUND CONTEXT', risk: 'LOW', color: '#00c48c' },
    { country: 'Ethiopia', flag: '🇪🇹', amount: '$1.0bn', instrument: 'Eurobond 6.625%', maturity: 'Defaulted — Tigray Fano Insurrection Active', risk: 'CRITICAL', color: '#ff3b3b' },
    { country: 'Senegal', flag: '🇸🇳', amount: 'NEW BOND 7.25%', instrument: 'Government Bond', maturity: 'LISTED AUG 10 — FAYE-SONKO WAR — IMF MAX RISK', risk: 'CRITICAL', color: '#ff3b3b' },
    { country: 'Angola', flag: '🇦🇴', amount: '$1.8bn', instrument: 'Eurobond', maturity: 'Q3 2026 — BRENT $89 ABOVE $78 BREAKEVEN', risk: 'MEDIUM', color: '#f5a623' },
    { country: 'Egypt', flag: '🇪🇬', amount: '$1.4bn', instrument: 'IMF Repurchase', maturity: 'Q3 2026', risk: 'HIGH', color: '#ff3b3b' },
    { country: 'Zambia', flag: '🇿🇲', amount: 'Post-Restructuring + $255m Lobito', instrument: 'Bilateral + Eurobond + AfDB', maturity: 'HICHILEMA WINS — INCOMING SADC CHAIR', risk: 'LOW', color: '#00c48c' },
    { country: 'Ivory Coast', flag: '🇨🇮', amount: '$1.3bn', instrument: 'Eurobond 5.39% 15yr', maturity: 'ISSUED — BENCHMARK CREDIT', risk: 'LOW', color: '#00c48c' },
    { country: 'Ghana', flag: '🇬🇭', amount: '$0.8bn', instrument: 'Post-Restructuring Bilateral', maturity: 'Q3-Q4 2026 — GOLD ATH + GHS STABILISING', risk: 'LOW', color: '#00c48c' },
  ],

  commodityExposure: [
    { country: 'Nigeria', flag: '🇳🇬', primary: 'Oil/Gas', exposure: 'HIGH', gdpShare: '8%', revenueShare: '65%', price2026: '$89', fiscalBreakeven: '$92/bbl', breakevenNote: 'NEAR BREAKEVEN — NIGER KIDNAPPING — DANGOTE IPO', trend: '↑', risk: 'HIGH' },
    { country: 'Angola', flag: '🇦🇴', primary: 'Oil', exposure: 'VERY HIGH', gdpShare: '45%', revenueShare: '80%', price2026: '$89', fiscalBreakeven: '$78/bbl', breakevenNote: 'ABOVE BREAKEVEN — LOBITO CORRIDOR', trend: '↑', risk: 'LOW' },
    { country: 'Ghana', flag: '🇬🇭', primary: 'Gold/Oil/Cocoa', exposure: 'MEDIUM', gdpShare: '15%', revenueShare: '35%', price2026: '$4,461/oz', fiscalBreakeven: '$1,800/oz', breakevenNote: '2.5X ATH WINDFALL — GHS STABILISING', trend: '↑', risk: 'LOW' },
    { country: 'Zambia', flag: '🇿🇲', primary: 'Copper', exposure: 'VERY HIGH', gdpShare: '12%', revenueShare: '70%', price2026: '$6.61/lb', fiscalBreakeven: '$5.50/lb', breakevenNote: 'ABOVE BREAKEVEN — HICHILEMA WINS', trend: '↑', risk: 'LOW' },
    { country: 'South Africa', flag: '🇿🇦', primary: 'Gold/Platinum', exposure: 'HIGH', gdpShare: '8%', revenueShare: '40%', price2026: '$4,461/oz', fiscalBreakeven: '$1,600/oz', breakevenNote: '2.8X ATH WINDFALL — ZAR 16.01 STRONGEST', trend: '↑', risk: 'LOW' },
    { country: 'DRC', flag: '🇨🇩', primary: 'Cobalt/Copper/Gold', exposure: 'VERY HIGH', gdpShare: '35%', revenueShare: '70%', price2026: 'Cobalt $32,000/t', fiscalBreakeven: 'N/A', breakevenNote: 'EBOLA 2,690 — WORST IN HISTORY TRAJECTORY', trend: '↓', risk: 'CRITICAL' },
    { country: 'Sudan', flag: '🇸🇩', primary: 'Gold', exposure: 'VERY HIGH', gdpShare: '15%', revenueShare: '40%', price2026: '$4,461/oz', fiscalBreakeven: 'N/A', breakevenNote: 'EU BAN — RSF NYALA MOBILISATION — US SANCTIONS', trend: '↓', risk: 'CRITICAL' },
  ],

  riskTable: [
    { country: 'NIGERIA', cds: 360, delta: '+15', bond: '-0.7pts', fx: '-12.0%', signal: '600 KIDNAPPED 30 KILLED NIGER STATE — TINUBU RESCUE', color: '#ff3b3b' },
    { country: 'DRC', cds: 0, delta: 'N/A', bond: 'N/A', fx: 'N/A', signal: 'EBOLA 2,690 DEAD 47.9% CFR — WORST IN HISTORY PATH', color: '#ff3b3b' },
    { country: 'TANZANIA', cds: 0, delta: 'N/A', bond: 'N/A', fx: 'N/A', signal: 'VP NCHIMBI RESIGNS — EAST AFRICA POLITICAL SIGNAL', color: '#ff3b3b' },
    { country: 'SOUTH AFRICA', cds: 178, delta: '-10', bond: '+0.5pts', fx: '-11.9%', signal: 'EMPLOYERS FIRE FOREIGN WORKERS — ZAR 16.01 STRONGEST', color: '#f5a623' },
    { country: 'ZIMBABWE', cds: 0, delta: 'N/A', bond: 'N/A', fx: 'N/A', signal: 'MNANGAGWA CONCOURT SENATE PACKING — CHAMISA NEW MOVE', color: '#ff3b3b' },
    { country: 'ZAMBIA', cds: 340, delta: '-95', bond: '+3.5pts', fx: '-32.9%', signal: 'HICHILEMA WINS 61% — INCOMING SADC CHAIR — ZMW STABLE', color: '#00c48c' },
    { country: 'GHANA', cds: 205, delta: '-35', bond: '+2.2pts', fx: '+5.2%', signal: 'GOLD $4,461 WINDFALL — GHS 11.05 — IMF COMPLETE', color: '#00c48c' },
    { country: 'IVORY COAST', cds: 178, delta: '-27', bond: '+1.7pts', fx: '+1.2%', signal: '$1.3BN EUROBOND — GAS PIPELINE — BENCHMARK', color: '#00c48c' },
  ],

  fxHistory: [
    { date: 'May 19', NGN: 1370.31, GHS: 13.27, KES: 129.50, EGP: 54.69, ZAR: 18.20, UGX: 3710, ZMW: 19.11, XOF: 610 },
    { date: 'May 22', NGN: 1370.31, GHS: 12.80, KES: 129.50, EGP: 53.50, ZAR: 18.40, UGX: 3710, ZMW: 19.11, XOF: 610 },
    { date: 'May 26', NGN: 1371.98, GHS: 11.90, KES: 129.50, EGP: 53.00, ZAR: 18.10, UGX: 3730, ZMW: 19.08, XOF: 612 },
    { date: 'May 28', NGN: 1371.98, GHS: 11.40, KES: 129.20, EGP: 52.50, ZAR: 17.20, UGX: 3758, ZMW: 19.04, XOF: 615 },
    { date: 'May 30', NGN: 1354.23, GHS: 10.70, KES: 129.03, EGP: 52.22, ZAR: 16.30, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 1', NGN: 1354.23, GHS: 10.72, KES: 129.41, EGP: 52.22, ZAR: 16.30, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 4', NGN: 1364.68, GHS: 11.15, KES: 129.53, EGP: 52.22, ZAR: 16.31, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 8', NGN: 1360.73, GHS: 11.22, KES: 129.53, EGP: 52.22, ZAR: 16.52, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 11', NGN: 1360.73, GHS: 11.22, KES: 129.41, EGP: 52.22, ZAR: 16.26, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 12', NGN: 1360.73, GHS: 11.20, KES: 129.45, EGP: 52.22, ZAR: 16.16, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 15', NGN: 1360.73, GHS: 11.20, KES: 129.48, EGP: 52.22, ZAR: 16.28, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 18', NGN: 1357.03, GHS: 11.18, KES: 129.54, EGP: 52.22, ZAR: 16.44, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 22', NGN: 1357.03, GHS: 11.15, KES: 129.54, EGP: 52.22, ZAR: 16.55, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 25', NGN: 1357.03, GHS: 11.12, KES: 129.54, EGP: 52.22, ZAR: 16.27, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 30', NGN: 1357.03, GHS: 11.10, KES: 129.54, EGP: 52.22, ZAR: 16.40, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jul 1', NGN: 1357.03, GHS: 11.08, KES: 129.54, EGP: 52.22, ZAR: 16.55, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jul 6', NGN: 1370.00, GHS: 11.35, KES: 129.50, EGP: 52.22, ZAR: 16.41, UGX: 3660.00, ZMW: 19.02, XOF: 570.00 },
    { date: 'Jul 13', NGN: 1378.00, GHS: 11.42, KES: 129.48, EGP: 52.22, ZAR: 16.47, UGX: 3670.00, ZMW: 19.02, XOF: 572.00 },
    { date: 'Jul 16', NGN: 1378.00, GHS: 11.47, KES: 129.42, EGP: 52.22, ZAR: 16.40, UGX: 3674.80, ZMW: 19.02, XOF: 574.71 },
    { date: 'Jul 18', NGN: 1378.00, GHS: 11.45, KES: 129.10, EGP: 52.22, ZAR: 16.03, UGX: 3674.80, ZMW: 19.02, XOF: 574.71 },
    { date: 'Jul 20', NGN: 1377.96, GHS: 11.44, KES: 129.04, EGP: 52.22, ZAR: 16.48, UGX: 3674.80, ZMW: 19.02, XOF: 574.71 },
    { date: 'Jul 22', NGN: 1376.00, GHS: 11.44, KES: 129.04, EGP: 52.22, ZAR: 16.46, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Jul 27', NGN: 1361.00, GHS: 11.43, KES: 129.04, EGP: 52.22, ZAR: 16.75, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Jul 28', NGN: 1363.00, GHS: 11.43, KES: 129.04, EGP: 52.22, ZAR: 16.62, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Jul 29', NGN: 1363.00, GHS: 11.43, KES: 129.04, EGP: 52.22, ZAR: 16.62, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Jul 30', NGN: 1363.00, GHS: 11.42, KES: 129.04, EGP: 52.22, ZAR: 16.62, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 1', NGN: 1363.00, GHS: 11.41, KES: 129.04, EGP: 52.22, ZAR: 16.52, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 3', NGN: 1363.00, GHS: 11.66, KES: 129.04, EGP: 52.22, ZAR: 16.55, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 5', NGN: 1363.00, GHS: 11.72, KES: 129.04, EGP: 52.22, ZAR: 16.32, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 7', NGN: 1363.00, GHS: 11.69, KES: 129.04, EGP: 52.22, ZAR: 16.14, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 10', NGN: 1363.00, GHS: 11.60, KES: 129.04, EGP: 52.22, ZAR: 16.20, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 12', NGN: 1363.00, GHS: 11.75, KES: 129.04, EGP: 52.22, ZAR: 16.20, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 14', NGN: 1363.00, GHS: 11.46, KES: 129.04, EGP: 52.22, ZAR: 16.20, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 15', NGN: 1363.00, GHS: 11.30, KES: 129.04, EGP: 52.22, ZAR: 16.18, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 16', NGN: 1363.00, GHS: 10.90, KES: 129.04, EGP: 52.22, ZAR: 16.17, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 17', NGN: 1363.00, GHS: 10.95, KES: 129.04, EGP: 52.22, ZAR: 16.17, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 18', NGN: 1359.00, GHS: 11.05, KES: 129.04, EGP: 52.22, ZAR: 16.16, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 22', NGN: 1363.00, GHS: 11.08, KES: 129.04, EGP: 52.22, ZAR: 16.16, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 24', NGN: 1363.00, GHS: 11.20, KES: 129.04, EGP: 52.22, ZAR: 16.16, UGX: 3674.80, ZMW: 19.02, XOF: 574.92 },
    { date: 'Aug 25', NGN: 1347.00, GHS: 11.05, KES: 129.50, EGP: 52.22, ZAR: 16.01, UGX: 3674.80, ZMW: 19.02, XOF: 574.71 },
  ],
}
