export const content = {
  riskIndex: '94',
  riskStatus: 'CRITICAL',

  riskMonitor: {
    updated: 'June 28, 2026 09:00 UTC',
    overallScore: 94,
    trend: 'STABLE',
    drivers: ['Ramaphosa Appeals To Traditional Monarchs — Kings And Queens To Deploy Moral Authority Against Xenophobia', 'KZN: 12,000 Deported Ahead Of June 30 — March Organisers Pledge Peaceful Protests', 'Bafana Bafana vs Canada TODAY — Round Of 32 — World Cup Knockout On Eve Of June 30', 'June 30 TOMORROW — SAPS Maximum Deployment — Hotspots Identified — 2 Days To Outcome'],
    regions: [
      { region: 'East Africa', score: 97, trend: '→', color: '#ff3b3b' },
      { region: 'West Africa', score: 90, trend: '→', color: '#ff3b3b' },
      { region: 'North Africa', score: 76, trend: '→', color: '#ff3b3b' },
      { region: 'Southern Africa', score: 98, trend: '→', color: '#ff3b3b' },
      { region: 'Central Africa', score: 99, trend: '→', color: '#ff3b3b' },
    ]
  },

  sovereignAlerts: [
    { country: 'South Africa', flag: '🇿🇦', alert: 'JUNE 30 TOMORROW. Ramaphosa appeals to traditional monarchs — kings and queens — to deploy moral authority against xenophobia. Matsila Royal House responded with grave warning about tribal targeting in Limpopo. KZN Premier Ntuli: 12,000 undocumented immigrants deported so far. March organisers gave commitments that June 30 demonstrations will remain peaceful. Traditional leaders and community policing structures pledged to protect communities. SAPS hotspots identified including eThekwini. Zimbabwean consulate queue in Cape Town being moved to Epping Repatriation Centre. Bafana vs Canada TODAY — a win extends SA\'s World Cup narrative into the June 30 week.', severity: 'CRITICAL', color: '#ff3b3b' },
    { country: 'DRC/Uganda', flag: '🇨🇩', alert: 'Ebola third-largest outbreak on record — 1,000+ confirmed cases as of June 22. France confirmed first European case. White House seeking $1.4bn from Congress. Africa CDC upgraded response ask from $518m to $1.4bn. Contact tracing at 58% — WHO target 90-95%. Families storming quarantine centres, 150+ patient escapes since late May. No approved vaccine, no approved treatment for Bundibugyo strain. WHO risk classification has been revised given France case.', severity: 'CRITICAL', color: '#ff3b3b' },
    { country: 'Zimbabwe', flag: '🇿🇼', alert: 'Senate approved constitutional amendments June 24 — 75 senators in favour. Direct presidential elections ABOLISHED. Term extended to 2030. Elections postponed 2028→2030. Only Mnangagwa signature needed. AU and Western governments yet to issue formal condemnation. Most consequential African democratic regression of the decade. Mnangagwa signature expected this week.', severity: 'CRITICAL', color: '#ff3b3b' },
    { country: 'Senegal', flag: '🇸🇳', alert: 'IMF visit concluded June 15-19 without deal. Statement June 22: discussions "on plans to navigate challenges ahead." No programme, no timeline. June 30 target missed. Eurobond issuance planned — first since 2025. Authorities "confident" of concluding programme "soon." Structural risk unchanged: 132% debt/GDP, $9.7bn obligations 2026. Q3 2026 programme announcement now base case.', severity: 'HIGH', color: '#f5a623' },
    { country: 'Ethiopia', flag: '🇪🇹', alert: 'Post-election conflict live — US TPLF visa restrictions confirmed June 18. Hundreds of thousands displaced. Pretoria Agreement collapsed. ENDF-TPLF clashes confirmed. Eritrea Red Sea tensions. Abiy third term confirmed — war risk active from day one of new mandate. Horn compound risk at maximum.', severity: 'CRITICAL', color: '#ff3b3b' },
  ],

  featuredSignal: {
    title: 'RAMAPHOSA APPEALS TO KINGS AND QUEENS — 12,000 DEPORTED — MARCH ORGANISERS PLEDGE PEACE — BAFANA VS CANADA TODAY — JUNE 30 IS TOMORROW',
    body: 'June 28 — the final Sunday of the most consequential month in African sovereign risk this decade. Ramaphosa has made an extraordinary appeal to South Africa\'s traditional monarchs — its kings and queens — to deploy their moral authority against xenophobic violence. The Matsila Royal House in Limpopo responded with a grave warning about a dangerous new dimension: the deliberate targeting of communities along tribal lines. KZN Premier Ntuli confirmed that 12,000 undocumented immigrants have already been deported ahead of June 30 — and that march organisers have given commitments that demonstrations will remain peaceful. Traditional leaders and community policing structures have pledged to help protect communities and infrastructure. The June 30 protests are scheduled for TOMORROW. The Zimbabweans queued outside the Cape Town consulate are being moved to the Epping Repatriation Centre. Bafana Bafana face Canada in the Round of 32 today at Los Angeles Stadium — a result that would put South Africa into the Round of 16 on the same day as June 30. The World Cup narrative and the xenophobia deadline are converging on the same 48-hour window.',
    tag: 'JUNE 28 CRITICAL SIGNAL',
    color: '#ff3b3b',
    author: 'Lord Fiifi Quayle',
    date: 'June 28, 2026',
  },

  pressureMap: [
    { country: 'Nigeria', flag: '🇳🇬', outlook: 'Negative', status: 'STRESSED', statusColor: '#ff3b3b', cds: '415', fxPressure: 'LOW', liquidity: 'WATCH' },
    { country: 'Ghana', flag: '🇬🇭', outlook: 'Cautious', status: 'WATCH', statusColor: '#f5a623', cds: '232', fxPressure: 'MODERATE', liquidity: 'STABLE' },
    { country: 'Kenya', flag: '🇰🇪', outlook: 'Cautious', status: 'WATCH', statusColor: '#f5a623', cds: '192', fxPressure: 'MODERATE', liquidity: 'WATCH' },
    { country: 'Egypt', flag: '🇪🇬', outlook: 'Cautious', status: 'WATCH', statusColor: '#f5a623', cds: '568', fxPressure: 'MODERATE', liquidity: 'WATCH' },
    { country: 'South Africa', flag: '🇿🇦', outlook: 'Negative', status: 'STRESSED', statusColor: '#ff3b3b', cds: '198', fxPressure: 'MODERATE', liquidity: 'TIGHT' },
    { country: 'Senegal', flag: '🇸🇳', outlook: 'Negative', status: 'WATCH', statusColor: '#f5a623', cds: '820', fxPressure: 'HIGH', liquidity: 'TIGHT' },
  ],

  whatMattersNow: [
    { title: 'RAMAPHOSA APPEALS TO TRADITIONAL MONARCHS — KINGS AND QUEENS — MORAL AUTHORITY AGAINST XENOPHOBIA', body: 'In an extraordinary move, President Ramaphosa has appealed to South Africa\'s traditional monarchs — its kings and queens — to deploy their moral authority to extinguish anti-foreigner violence ahead of June 30. The appeal reflects the limits of conventional security and political tools: SAPS deployed, SANDF on standby, 5-point plan announced, diplomatic envoys sent — and yet the violence continued. Traditional institutions carry moral authority in communities where state legitimacy is contested. The Matsila Royal House in Limpopo responded with a grave warning: the unrest is developing a new dimension of deliberate tribal targeting within provinces — attacks not just on foreigners but along ethnic lines. This adds a Limpopo dimension to the KZN, Gauteng, Western Cape and Eastern Cape hotspot picture.', icon: '👑' },
    { title: 'KZN: 12,000 DEPORTED — MARCH ORGANISERS PLEDGE PEACEFUL PROTESTS — HOTSPOTS IDENTIFIED', body: 'KZN Premier Ntuli confirmed 12,000 undocumented immigrants deported so far ahead of June 30. Intelligence has identified hotspots including parts of eThekwini. Government secured commitments from march organisers that demonstrations will remain peaceful. Traditional leaders and community policing structures pledged to protect communities and infrastructure. Ntuli cautioned against political parties exploiting the marches. Security planning informed by hotspot intelligence. Malawian killed in Pietermaritzburg last week — Ntuli said the incident occurred in a crime-ridden informal settlement, not along a protest route. KZN is the most volatile province entering June 30.', icon: '🚨' },
    { title: 'BAFANA VS CANADA TODAY — ROUND OF 32 — LOS ANGELES STADIUM — WORLD CUP KNOCKOUT', body: 'South Africa face Canada in the Round of 32 today at Los Angeles Stadium — first knockout stage fixture for both nations. Both made World Cup history by reaching the knockout rounds. Canada: Alphonso Davies available for selection. Coach Marsch pledged aggressive start. Jonathan David hat-trick vs Qatar in group stage. Bafana: Zwane still suspended (3-match ban following red card). Mokoena returns from one-game suspension. Williams in inspired form. A Bafana win today would put South Africa into the Round of 16 — results announced during the June 30 window. The World Cup narrative is the most powerful counter-signal to the xenophobia deadline the GNU possesses.', icon: '⚽' },
    { title: 'EBOLA: FRANCE FIRST EUROPEAN CASE — WHITE HOUSE $1.4BN CONGRESS ASK — 1,000+ CONFIRMED', body: 'Ebola is now the third-largest outbreak on record — 1,000+ confirmed as of June 22. France confirmed first European case — revised WHO global risk assessment. White House seeking $1.4bn from Congress. Africa CDC upgraded ask from $518m to $1.4bn. Contact tracing at 58%. Families still storming quarantine centres. DRC introduced free healthcare for all illnesses in Ituri. 150+ patient escapes since late May. No approved vaccine, no approved treatment for Bundibugyo strain. Most serious Bundibugyo outbreak in history.', icon: '🔴' },
  ],

  insight1: {
    title: 'RAMAPHOSA\'S APPEAL TO TRADITIONAL MONARCHS IS THE MOST SIGNIFICANT GOVERNANCE TOOL DEPLOYED YET — AND THE MOST REVEALING ABOUT THE LIMITS OF STATE POWER',
    body: 'When a president appeals to traditional monarchs to deploy their moral authority, he is acknowledging that the institutional tools of a democratic state — police, courts, parliament, diplomatic envoys — are insufficient for the specific challenge he faces. Xenophobic violence in South Africa\'s informal settlements and peri-urban communities is not susceptible to conventional deterrence because the communities where it occurs are precisely those where state legitimacy is most contested and state presence is most limited. Traditional kings and queens — amakhosi — command moral authority in exactly these spaces. The Matsila Royal House\'s response, warning about tribal targeting in Limpopo, reveals a new dimension that none of the standard security frameworks can address: the unrest is developing from anti-foreigner violence into intra-South African ethnic targeting. This is the most dangerous evolution of the crisis.',
    conclusion: 'THE ROYAL APPEALS SIGNAL THAT RAMAPHOSA HAS EXHAUSTED THE CONVENTIONAL GOVERNANCE TOOLKIT AND IS NOW DEPLOYING TRADITIONAL AUTHORITY AS A LAST-RESORT MORAL DETERRENT. THE MATSILA WARNING ABOUT TRIBAL TARGETING IS THE MOST ALARMING NEW DIMENSION OF THE JUNE 30 CRISIS.',
  },

  insight2: {
    title: 'THE 12,000 DEPORTATION FIGURE FROM KZN IS THE STATE\'S MOST CONCRETE RESPONSE TO MARCH AND MARCH\'S DEMANDS — AND ITS MOST POLITICALLY CONSEQUENTIAL',
    body: 'March and March\'s core demand was that the state enforce immigration laws and remove undocumented migrants. KZN Premier Ntuli confirming 12,000 deportations is the state saying: we are doing what you asked. This is simultaneously a security measure, a political concession, and a humanitarian concern — because among those 12,000 may be asylum seekers, people with pending documentation, and legal residents caught in enforcement sweeps. The Malawian who died after being placed in the trunk of a police car — documented by HRW — is the extreme expression of what enforcement without due process looks like. The deportation numbers give Ramaphosa a policy achievement to present to the movements on June 30. But they also document state behaviour that will face international and legal scrutiny long after June 30 has passed.',
    conclusion: 'THE 12,000 KZN DEPORTATIONS ARE THE STATE\'S MOST CONCRETE JUNE 30 DELIVERABLE. THEY SATISFY MARCH AND MARCH\'S CORE DEMAND WHILE GENERATING HUMANITARIAN AND LEGAL RISKS THAT WILL OUTLAST THE DEADLINE. WATCH FOR HRW AND UN RESPONSE TO DEPORTATION PROCESS DOCUMENTATION.',
  },

  brief: {
    week: '27',
    title: 'WEEK 27 SUNDAY: RAMAPHOSA TO KINGS AND QUEENS, 12,000 DEPORTED, BAFANA VS CANADA TODAY, JUNE 30 TOMORROW',
    body: 'The final Sunday before June 30. Ramaphosa appealed to South Africa\'s traditional monarchs to deploy moral authority against xenophobia — the Matsila Royal House warned about tribal targeting in Limpopo. KZN Premier confirmed 12,000 deported, march organisers pledged peaceful protests, traditional leaders and CPF structures pledged to protect communities. Bafana Bafana face Canada in the Round of 32 today at Los Angeles Stadium — both nations making history in their first World Cup knockout game. June 30 is tomorrow — SAPS hotspots identified, SANDF on standby, R600m operation deployed. Senegal\'s IMF programme is deferred to Q3. Ethiopia\'s post-election conflict is live. Zimbabwe\'s Mnangagwa needs only to sign the constitutional amendments. Ebola at 1,000+ confirmed, France first European case. The continent\'s most consequential week closes tomorrow.',
  },

  fxRates: {
    NGN: '1,357.03',
    GHS: '11.20',
    KES: '129.54',
    EGP: '52.22',
    XOF: '569.32',
    ZAR: '16.39',
    ETB: '158.00',
    TZS: '2,650.00',
    UGX: '3,645.50',
    MAD: '9.75',
    XAF: '615.00',
    ZMW: '19.02',
    AOA: '915.00',
    MZN: '63.80',
  },

  signals: [
    { time: '09:30:00', signal: 'Ramaphosa appeals to SA traditional monarchs — kings and queens — to deploy moral authority against xenophobia ahead of June 30. Matsila Royal House (Limpopo) responded with grave warning: deliberate tribal targeting emerging as new dimension of unrest. Conventional security toolkit exhausted — traditional institutions now final deterrence tool.', detail: 'HIGH', type: 'ALERT', tag: 'POLITICAL RISK', country: 'ZAR' },
    { time: '09:15:00', signal: 'KZN Premier Ntuli: 12,000 undocumented immigrants deported so far ahead of June 30. Hotspots identified including eThekwini. March organisers gave commitments — peaceful demonstrations pledged. Traditional leaders + CPF structures pledged to protect communities and infrastructure. Political parties warned against exploiting marches.', detail: 'MEDIUM', type: 'INFO', tag: 'POLITICAL RISK', country: 'ZAR' },
    { time: '09:00:00', signal: 'BAFANA VS CANADA TODAY — Round of 32, Los Angeles Stadium. First knockout fixture for both nations. Zwane suspended. Mokoena returns. Davies available for Canada. Marsch pledged aggressive start. A win puts SA into Round of 16 — results on same day as June 30 tomorrow. World Cup narrative is GNU\'s most powerful soft power asset.', detail: 'LOW', type: 'INFO', tag: 'GEOPOLITICAL', country: 'ZAR' },
    { time: '08:45:00', signal: 'June 30 TOMORROW. Zimbabwe consulate queue in Cape Town moved to Epping Repatriation Centre. 68-seater buses leaving daily but crowd growing. Hotspots across Western Cape particularly in rural areas. Kleinmond and Gansbaai experienced unrest previously. Police leaves suspended nationwide.', detail: 'HIGH', type: 'ALERT', tag: 'POLITICAL RISK', country: 'ZAR' },
    { time: '08:30:00', signal: 'Ebola: 1,000+ confirmed — third-largest outbreak on record. France first European case. White House $1.4bn Congress ask. Africa CDC upgraded ask. Contact tracing 58%. Free healthcare Ituri. 150+ patient escapes. No vaccine, no treatment. WHO risk assessment revised given France case.', detail: 'HIGH', type: 'ALERT', tag: 'HEALTH RISK', country: 'AFRICA' },
    { time: '08:15:00', signal: 'Ethiopia: Post-election conflict live. US TPLF visa restrictions confirmed June 18. Hundreds of thousands displaced. Pretoria Agreement collapsed. Eritrea Red Sea tensions. Abiy third term — war risk active. Horn compound risk at maximum. Most dangerous Horn window since 2020.', detail: 'HIGH', type: 'ALERT', tag: 'SECURITY RISK', country: 'ETB' },
    { time: '08:00:00', signal: 'Senegal: IMF visit concluded no deal. Q3 2026 programme now base case. Eurobond issuance planned. Bonds rallied from 50.6c. Structural risk: 132% debt/GDP, $9.7bn obligations. Engagement active. Zimbabwe: Mnangagwa signature pending — direct elections abolished, term to 2030.', detail: 'MEDIUM', type: 'INFO', tag: 'CREDIT UPDATE', country: 'XOF' },
    { time: '07:45:00', signal: 'LIVE FX June 28: NGN 1,357.03 | GHS 11.20 | KES 129.54 | EGP 52.22 | ZAR 16.39 | UGX 3,645.50 | ZMW 19.02 | XOF 569.32. ZAR holding through the peak risk window — markets pricing June 30 as contained given march size data and peacekeeping commitments. Watch ZAR Monday open after June 30 outcome.', detail: 'LOW', type: 'INFO', tag: 'FX UPDATE', country: 'AFRICA' },
  ],

  heatMap: [
    { country: 'Nigeria', flag: '🇳🇬', score: 92, fiscal: 60, fx: 42, debt: 60, political: 96, external: 86 },
    { country: 'Ghana', flag: '🇬🇭', score: 38, fiscal: 34, fx: 46, debt: 34, political: 30, external: 40 },
    { country: 'Kenya', flag: '🇰🇪', score: 84, fiscal: 80, fx: 66, debt: 86, political: 86, external: 84 },
    { country: 'Ethiopia', flag: '🇪🇹', score: 98, fiscal: 68, fx: 74, debt: 72, political: 99, external: 98 },
    { country: 'South Africa', flag: '🇿🇦', score: 97, fiscal: 80, fx: 50, debt: 70, political: 99, external: 96 },
    { country: 'Senegal', flag: '🇸🇳', score: 72, fiscal: 76, fx: 62, debt: 78, political: 68, external: 70 },
    { country: 'Zimbabwe', flag: '🇿🇼', score: 96, fiscal: 78, fx: 82, debt: 84, political: 99, external: 92 },
    { country: 'DRC', flag: '🇨🇩', score: 99, fiscal: 88, fx: 90, debt: 82, political: 96, external: 99 },
  ],

  currencyStress: [
    { code: 'NGN', country: 'Nigeria', rate: '1,357.03', change: '-13.83%', stress: 'MODERATE', ytd: '-3.40%', color: '#f5a623' },
    { code: 'GHS', country: 'Ghana', rate: '11.20', change: '+8.81%', stress: 'MODERATE', ytd: '+12.40%', color: '#f5a623' },
    { code: 'KES', country: 'Kenya', rate: '129.54', change: '+0.07%', stress: 'MODERATE', ytd: '-0.93%', color: '#f5a623' },
    { code: 'EGP', country: 'Egypt', rate: '52.22', change: '-4.32%', stress: 'HIGH', ytd: '-4.51%', color: '#ff3b3b' },
    { code: 'ZAR', country: 'South Africa', rate: '16.39', change: '-10.70%', stress: 'MODERATE', ytd: '+10.70%', color: '#f5a623' },
    { code: 'UGX', country: 'Uganda', rate: '3,645.50', change: '-3.31%', stress: 'ELEVATED', ytd: '-3.31%', color: '#ff3b3b' },
    { code: 'ZMW', country: 'Zambia', rate: '19.02', change: '-32.91%', stress: 'HIGH', ytd: '-32.91%', color: '#ff3b3b' },
    { code: 'XOF', country: 'Mali/Senegal', rate: '569.32', change: '-7.43%', stress: 'MODERATE', ytd: '-7.43%', color: '#f5a623' },
  ],

  elections: [
    { country: 'South Africa', flag: '🇿🇦', date: 'June 30 — TOMORROW', type: 'Municipal Elections', risk: 'CRITICAL', note: 'June 30 TOMORROW. Ramaphosa appealed to kings and queens. 12,000 deported. March organisers pledged peace. Traditional leaders and CPF pledged to protect communities. Matsila Royal House warned of tribal targeting in Limpopo. Bafana vs Canada today.', color: '#ff3b3b' },
    { country: 'Zimbabwe', flag: '🇿🇼', date: 'Mnangagwa Signature Pending', type: 'Constitutional Amendment', risk: 'CRITICAL', note: 'Senate approved June 24. Direct elections abolished. Term to 2030. Elections postponed to 2030. Only Mnangagwa signature needed. AU response absent. Most consequential African democratic regression of decade.', color: '#ff3b3b' },
    { country: 'Ethiopia', flag: '🇪🇹', date: 'Post-Election Conflict Live', type: 'General Election', risk: 'CRITICAL', note: 'US TPLF visa restrictions. Hundreds of thousands displaced. Pretoria Agreement collapsed. War risk active. Eritrea tensions. Horn at maximum risk.', color: '#ff3b3b' },
    { country: 'Kenya', flag: '🇰🇪', date: 'June 25 Contained — Accountability Next', type: 'Political Crisis', risk: 'HIGH', note: '355 arrested June 25. No storming. Finance Bill law. Sh2bn reparations announced. Accountability implementation is next test. Risk eased from peak.', color: '#f5a623' },
    { country: 'Senegal', flag: '🇸🇳', date: 'IMF Q3 2026 Programme Now Base Case', type: 'Debt Crisis', risk: 'HIGH', note: 'IMF visit no deal. Q3 2026 programme expected. Eurobond planned. Bonds rallied. Structural risk unchanged. Engagement active.', color: '#f5a623' },
    { country: 'Nigeria', flag: '🇳🇬', date: 'Early 2027 — ISSP Active', type: 'General Election', risk: 'CRITICAL', note: 'ISSP first operations in 6 years. 842 killed May. Multi-vector security peak. 2027 election risk tier-1.', color: '#ff3b3b' },
    { country: 'Somalia', flag: '🇸🇴', date: 'Constitutional Crisis', type: 'Constitutional Crisis', risk: 'CRITICAL', note: 'Ceasefire holding. Opposition "former president." Al-Shabaab active. US resumed airstrikes. Structural crisis ongoing.', color: '#ff3b3b' },
  ],

  debtMaturities: [
    { country: 'Senegal', flag: '🇸🇳', amount: 'PAID EARLY', instrument: 'Bond Coupons', maturity: 'Q3 2026 IMF PROGRAMME EXPECTED', risk: 'MEDIUM', color: '#f5a623' },
    { country: 'Senegal', flag: '🇸🇳', amount: '$1.8bn', instrument: 'IMF Programme', maturity: 'Disbursement Frozen — Q3 Expected', risk: 'HIGH', color: '#f5a623' },
    { country: 'Kenya', flag: '🇰🇪', amount: '$2.0bn', instrument: 'Eurobond', maturity: 'Q2 2026', risk: 'HIGH', color: '#f5a623' },
    { country: 'Egypt', flag: '🇪🇬', amount: '$2.1bn', instrument: 'Eurobond', maturity: 'Q2 2026', risk: 'HIGH', color: '#ff3b3b' },
    { country: 'Egypt', flag: '🇪🇬', amount: '$1.4bn', instrument: 'IMF Repurchase', maturity: 'Q3 2026', risk: 'HIGH', color: '#ff3b3b' },
    { country: 'Angola', flag: '🇦🇴', amount: '$1.8bn', instrument: 'Eurobond', maturity: 'Q3 2026', risk: 'HIGH', color: '#ff3b3b' },
    { country: 'South Africa', flag: '🇿🇦', amount: '$2.2bn', instrument: 'Domestic Bond Rollovers', maturity: 'Q2-Q3 2026', risk: 'HIGH', color: '#ff3b3b' },
    { country: 'Ghana', flag: '🇬🇭', amount: '$0.8bn', instrument: 'Post-Restructuring Bilateral', maturity: 'Q3-Q4 2026', risk: 'LOW', color: '#00c48c' },
  ],

  commodityExposure: [
    { country: 'Nigeria', flag: '🇳🇬', primary: 'Oil', exposure: 'HIGH', gdpShare: '8%', revenueShare: '65%', price2026: '$82', fiscalBreakeven: '$92/bbl', breakevenNote: 'BELOW BREAKEVEN', trend: '↑', risk: 'HIGH' },
    { country: 'Angola', flag: '🇦🇴', primary: 'Oil', exposure: 'VERY HIGH', gdpShare: '45%', revenueShare: '80%', price2026: '$82', fiscalBreakeven: '$78/bbl', breakevenNote: 'ABOVE BREAKEVEN', trend: '↓', risk: 'HIGH' },
    { country: 'Ghana', flag: '🇬🇭', primary: 'Gold/Oil/Cocoa', exposure: 'MEDIUM', gdpShare: '15%', revenueShare: '35%', price2026: '$3,200/oz', fiscalBreakeven: '$1,800/oz', breakevenNote: 'STRONG BUFFER', trend: '↑', risk: 'LOW' },
    { country: 'Zambia', flag: '🇿🇲', primary: 'Copper', exposure: 'VERY HIGH', gdpShare: '12%', revenueShare: '70%', price2026: '$9,800/t', fiscalBreakeven: '$7,500/t', breakevenNote: 'ABOVE BREAKEVEN', trend: '→', risk: 'MEDIUM' },
    { country: 'South Africa', flag: '🇿🇦', primary: 'Gold/Platinum', exposure: 'HIGH', gdpShare: '8%', revenueShare: '40%', price2026: '$3,200/oz', fiscalBreakeven: '$1,600/oz', breakevenNote: 'STRONG BUFFER', trend: '↑', risk: 'LOW' },
    { country: 'Kenya', flag: '🇰🇪', primary: 'Tea/Coffee', exposure: 'MEDIUM', gdpShare: '5%', revenueShare: '25%', price2026: 'Stable', fiscalBreakeven: 'N/A', breakevenNote: 'NON-COMMODITY', trend: '→', risk: 'MEDIUM' },
    { country: 'Egypt', flag: '🇪🇬', primary: 'Oil/Gas/Tourism', exposure: 'MEDIUM', gdpShare: '10%', revenueShare: '30%', price2026: '$82', fiscalBreakeven: '$70/bbl', breakevenNote: 'ABOVE BREAKEVEN', trend: '↑', risk: 'MEDIUM' },
  ],

  riskTable: [
    { country: 'SOUTH AFRICA', cds: 198, delta: '+42', bond: '-2.1pts', fx: '+10.7%', signal: 'JUNE 30 TOMORROW — ROYALS DEPLOYED — 12K DEPORTED', color: '#ff3b3b' },
    { country: 'DRC', cds: 0, delta: 'N/A', bond: 'N/A', fx: 'N/A', signal: 'EBOLA 1000+ — FRANCE CASE — $1.4BN ASK', color: '#ff3b3b' },
    { country: 'ZIMBABWE', cds: 0, delta: 'N/A', bond: 'N/A', fx: 'N/A', signal: 'ELECTIONS ABOLISHED — SIGNATURE PENDING', color: '#ff3b3b' },
    { country: 'ETHIOPIA', cds: 520, delta: '+60', bond: '-3.0pts', fx: '-0.9%', signal: 'TPLF CONFLICT LIVE — POST-ELECTION WAR', color: '#ff3b3b' },
    { country: 'NIGERIA', cds: 415, delta: '+38', bond: '-1.9pts', fx: '-13.8%', signal: 'ISSP ACTIVE — MULTI-VECTOR SECURITY PEAK', color: '#ff3b3b' },
    { country: 'SENEGAL', cds: 820, delta: '-40', bond: '+0.8pts', fx: '-0.5%', signal: 'IMF NO DEAL — Q3 PROGRAMME BASE CASE', color: '#f5a623' },
    { country: 'KENYA', cds: 192, delta: '+25', bond: '-1.3pts', fx: '+0.1%', signal: 'JUNE 25 CONTAINED — ACCOUNTABILITY NEXT', color: '#f5a623' },
    { country: 'GHANA', cds: 232, delta: '-5', bond: '+0.4pts', fx: '+8.8%', signal: 'WORLD CUP ADVANCING — IMF COMPLETE', color: '#00c48c' },
  ],

  fxHistory: [
    { date: 'May 19', NGN: 1370.31, GHS: 13.27, KES: 129.50, EGP: 54.69, ZAR: 18.20, UGX: 3710, ZMW: 19.11, XOF: 610 },
    { date: 'May 20', NGN: 1370.31, GHS: 13.10, KES: 129.50, EGP: 53.90, ZAR: 18.45, UGX: 3710, ZMW: 19.11, XOF: 610 },
    { date: 'May 22', NGN: 1370.31, GHS: 12.80, KES: 129.50, EGP: 53.50, ZAR: 18.40, UGX: 3710, ZMW: 19.11, XOF: 610 },
    { date: 'May 23', NGN: 1370.31, GHS: 12.50, KES: 129.50, EGP: 53.20, ZAR: 18.35, UGX: 3710, ZMW: 19.11, XOF: 610 },
    { date: 'May 25', NGN: 1370.31, GHS: 12.20, KES: 129.50, EGP: 53.12, ZAR: 18.30, UGX: 3710, ZMW: 19.11, XOF: 610 },
    { date: 'May 26', NGN: 1371.98, GHS: 11.90, KES: 129.50, EGP: 53.00, ZAR: 18.10, UGX: 3730, ZMW: 19.08, XOF: 612 },
    { date: 'May 27', NGN: 1371.98, GHS: 11.66, KES: 129.50, EGP: 52.80, ZAR: 17.80, UGX: 3745, ZMW: 19.05, XOF: 613 },
    { date: 'May 28', NGN: 1371.98, GHS: 11.40, KES: 129.20, EGP: 52.50, ZAR: 17.20, UGX: 3758, ZMW: 19.04, XOF: 615 },
    { date: 'May 29', NGN: 1371.85, GHS: 11.10, KES: 129.10, EGP: 52.35, ZAR: 16.80, UGX: 3765, ZMW: 19.03, XOF: 615 },
    { date: 'May 30', NGN: 1354.23, GHS: 10.70, KES: 129.03, EGP: 52.22, ZAR: 16.30, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 1', NGN: 1354.23, GHS: 10.70, KES: 129.41, EGP: 52.22, ZAR: 16.30, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 2', NGN: 1364.68, GHS: 10.70, KES: 129.41, EGP: 52.22, ZAR: 16.24, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 3', NGN: 1364.68, GHS: 11.75, KES: 129.41, EGP: 52.22, ZAR: 16.36, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 4', NGN: 1364.68, GHS: 11.75, KES: 129.53, EGP: 52.22, ZAR: 16.31, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 5', NGN: 1361.39, GHS: 11.75, KES: 129.53, EGP: 52.22, ZAR: 16.56, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 8', NGN: 1360.73, GHS: 11.82, KES: 129.53, EGP: 52.22, ZAR: 16.52, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 9', NGN: 1360.73, GHS: 11.82, KES: 129.53, EGP: 52.22, ZAR: 16.52, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 10', NGN: 1360.73, GHS: 11.82, KES: 129.41, EGP: 52.22, ZAR: 16.58, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 11', NGN: 1360.73, GHS: 11.82, KES: 129.41, EGP: 52.22, ZAR: 16.56, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 12', NGN: 1360.73, GHS: 11.13, KES: 129.45, EGP: 52.22, ZAR: 16.26, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 15', NGN: 1360.73, GHS: 11.13, KES: 129.48, EGP: 52.22, ZAR: 16.28, UGX: 3770, ZMW: 19.02, XOF: 615 },
    { date: 'Jun 16', NGN: 1357.50, GHS: 11.15, KES: 129.50, EGP: 52.22, ZAR: 16.14, UGX: 3700, ZMW: 19.02, XOF: 590 },
    { date: 'Jun 17', NGN: 1357.20, GHS: 11.18, KES: 129.52, EGP: 52.22, ZAR: 16.42, UGX: 3650, ZMW: 19.02, XOF: 575 },
    { date: 'Jun 18', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.18, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 19', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.53, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 20', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.30, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 22', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.42, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 23', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.39, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 24', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.39, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 25', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.39, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 26', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.39, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 27', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.39, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
    { date: 'Jun 28', NGN: 1357.03, GHS: 11.20, KES: 129.54, EGP: 52.22, ZAR: 16.39, UGX: 3645.50, ZMW: 19.02, XOF: 569.32 },
  ],
}
